services:
  rplidar:
    image: ghcr.io/screamlab/pros_jetson_driver_image:latest
    env_file:
      - .env
    devices:
      - "/dev/usb_lidar:/dev/usb_lidar"
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - my_bridge_network
    command: "ros2 launch /workspace/demo/rplidar.xml"

networks:
  my_bridge_network:
    driver: bridge
